openactive/openactive-test-suite

packages/openactive-integration-tests/test/integration-test.js, packages/openactive-integration-tests/test/test-helper.js
* Refactors the promise chains into await
* Moves the raw HTTP calls and result handling into helper funcs for each request type (so as to have modular components for future runs)
=> Clean up tests: await, separate out detailed logic into a helper

packages/openactive-broker-microservice/app.js, packages/openactive-broker-microservice/config/default.json, packages/openactive-integration-tests/package-lock.json, packages/openactive-integration-tests/package.json, packages/openactive-integration-tests/test/flows/book-and-cancel/book-and-customer-cancel-failure/book-shared.js, packages/openactive-integration-tests/test/flows/book-and-cancel/book-and-customer-cancel-success/book-shared.js, packages/openactive-integration-tests/test/shared-behaviours/validation.js, packages/openactive-integration-tests/test/templates/b-req.json, packages/openactive-integration-tests/test/templates/c1-req.json, packages/openactive-integration-tests/test/templates/c2-req.json
@ylt so the live reference implementation now passes validation against the latest `data-models` using the `data-model-validator`. I had to fix some minor bugs in this test suite to get them to pass (see this PR).
Rather than attempting to merge these in to your work, as I know you're doing some refactoring here, I've left this as a PR just so you can see the fixes.
Would you be able to just port these over to your new refactored code? You should see that all validation tests now pass.
Please do check out the results of C1, as it looks like the validation isn't running properly for that for some reason, but you may have already fixed this in your refactor?
=> Changes to pass validation

packages/openactive-integration-tests/test/flows/book-and-cancel/book-and-customer-cancel-failure/book-shared.js, packages/openactive-integration-tests/test/flows/book-and-cancel/book-and-customer-cancel-success/book-shared.js, packages/openactive-integration-tests/test/flows/confirm-availability/availability-confirmed/book-shared.js, packages/openactive-integration-tests/test/flows/confirm-availability/no-spaces-available/book-shared.js, packages/openactive-integration-tests/test/shared-behaviours/validation.js
Implements #32  
Makes the validation deterministically use a "OpenBookingError" if the response code is a non 2xx. Also adds in a custom validation error message in the case that the body is empty (and thus nothing to validate).
```
• C2
❌️ Server returned an error 500 (Internal Server Error) with an empty body.
❌️ should return 200 on success
❌️ offer should have price of 14.95
```
=> Add validation error handling

packages/openactive-integration-tests/test/flows/book-and-cancel/book-and-customer-cancel-failure/book-shared.js, packages/openactive-integration-tests/test/flows/book-and-cancel/book-and-customer-cancel-success/book-shared.js, packages/openactive-integration-tests/test/flows/confirm-availability/availability-confirmed/book-shared.js, packages/openactive-integration-tests/test/shared-behaviours/b.js, packages/openactive-integration-tests/test/shared-behaviours/c1.js, packages/openactive-integration-tests/test/shared-behaviours/c2.js
Point 5 on https://github.com/openactive/openactive-test-suite/issues/34
> "Generalise some of C1, C2 tests etc to provide shared examples that can be reused across shared test suites."
=> Shared behaviours

packages/openactive-integration-tests/package-lock.json, packages/openactive-integration-tests/package.json, packages/openactive-integration-tests/test/helpers/logger.js, packages/openactive-integration-tests/test/helpers/request-helper.js, packages/openactive-integration-tests/test/report-generator.js, packages/openactive-integration-tests/test/report-templates/report-cli.handlebars, packages/openactive-integration-tests/test/report-templates/report.md.handlebars
Addresses https://github.com/openactive/openactive-test-suite/issues/46
- Cleans out the titles so that the full test path isn't references
- Removes out sections without any info to display
- Renders out errors
Couple of other changes:
- Updated project dependencies to non-vulnerable versions
- ANSI stripping
=> Cleaner logging

CONTRIBUTING.md
Improve docs to include `feature/*` branch checking in CI
=> docs: Update to make feature CI mirroring clear

.github/workflows/reference-implementation.yml, CONTRIBUTING.md
Use `coverage/` so it doesn't conflict with convention
=> fix: Update to use coverage/ prefix

.github/workflows/reference-implementation.yml, README.md, package.json, packages/openactive-broker-microservice/package-lock.json, packages/openactive-broker-microservice/package.json, packages/openactive-integration-tests/README.md, packages/openactive-integration-tests/documentation/generator.js, packages/openactive-integration-tests/package.json, packages/openactive-integration-tests/run-specific-test.sh, packages/openactive-integration-tests/test/features/cancellation/customer-requested-cancellation/README.md, packages/openactive-integration-tests/test/features/core/availability-check/README.md, packages/openactive-integration-tests/test/features/core/dataset-site/README.md, packages/openactive-integration-tests/test/features/core/multiple-sellers/README.md, packages/openactive-integration-tests/test/features/core/simple-book-free-opportunities/README.md, packages/openactive-integration-tests/test/features/core/test-interface/README.md, packages/openactive-integration-tests/test/features/payment/simple-book-with-payment/README.md, packages/openactive-integration-tests/test/reporter.js, publish-example-output.sh, simple-ci.sh
openactive-test-suite's `npm test` has been repurposed, so that this runs the static checks.
The Booking API tests are now run with `npm start`. This fits with the NPM pattern where `npm test` tests the code itself and `npm start` runs the code. In this case, the code is tests, so the language can be confusing, admittedly
=> chore: Run static checks on CI

packages/openactive-integration-tests/test/features/core/availability-check/implemented/availability-confirmed-test.js, packages/openactive-integration-tests/test/helpers/feature-helper.js, packages/openactive-integration-tests/test/helpers/request-state.js
Relates to issue https://github.com/openactive/openactive-test-suite/issues/91
This means that VSCode will auto-complete things that have been typed e.g. 
and captures errors as you type e.g.
=> chore: Type the FeatureHelper.describeFeature function and its args

package.json
Remove the `--prefix` anti-pattern as it does not work on Windows, and replace with `cd`, as discussed in https://github.com/npm/npm/pull/10958
=> fix: Remove prefix anti-pattern

packages/test-interface-criteria/.eslintrc.json, packages/test-interface-criteria/package-lock.json, packages/test-interface-criteria/package.json
I've taken .eslintrc.json from openactive-integration-tests. Do we have preferred rules for this, or does this work?
=> chore: Add ESLint to test-interface-criteria

packages/openactive-integration-tests/test/helpers/logger.js, packages/openactive-integration-tests/test/helpers/request-helper.js, packages/openactive-integration-tests/test/types/chakram/index.d.ts
This was previously not passing params properly for get requests. It also had confusingly named arguments
=> fix: Fix request-helper._request function

.gitignore
Add WebStorm IDE files to `.gitignore`, so we don't accidentally check them in.
=> Ignore JetBrains IDE files

packages/openactive-broker-microservice/README.md, packages/openactive-broker-microservice/app.js
Feedback from working with Bookteq:
- Should be able to run without Orders feed completed (note it currently does, but accidentally, this PR fixes that)
- If there's an issue with zero IDs matching the harvester should fail, before the tests get a chance to run (as they will also all fail), otherwise the harvester should at least warn to assist debugging
=> fix: Add warning for Orphans and fix Orders feed ingestion

packages/openactive-integration-tests/test/features/core/agent-broker/implemented/customer-not-included-test.js, packages/openactive-integration-tests/test/helpers/flow-stages/b.js, packages/openactive-integration-tests/test/helpers/flow-stages/c1.js, packages/openactive-integration-tests/test/helpers/flow-stages/c2.js, packages/openactive-integration-tests/test/helpers/flow-stages/flow-stage-recipes.js, packages/openactive-integration-tests/test/helpers/flow-stages/flow-stage-utils.js, packages/openactive-integration-tests/test/helpers/flow-stages/index.js
Also, fix use of template for c1,c2,b, which have not taken into account new brokerRole positional arg in RequestHelper
-----
Depends on https://github.com/openactive/openactive-test-suite/pull/285
In order to test that this worked, I tried it out on an existing test, `customer-not-included`. It works. Hooray.
=> refactor: Add describeRunAndCheckIsValid() function for FlowStages which are expected to error

packages/openactive-integration-tests/test/features/approval/minimal-proposal/implemented/accept-proposal-book-test.js, packages/openactive-integration-tests/test/helpers/flow-stages/b.js
This means that it is no longer possible to accidentally exclude it in a new test (which would make random prepayment=unavailable tests fail
------
I did this because I notice that some of the existing PRs will randomly fail and should get a TS error
=> fix(flow-stages): B requires `prepayment` in its Input

packages/openactive-integration-tests/test/helpers/flow-stages/b.js, packages/openactive-integration-tests/test/helpers/flow-stages/order-feed-update.js, packages/openactive-integration-tests/test/helpers/flow-stages/test-interface-action.js, packages/openactive-integration-tests/test/shared-behaviours/test-recipes.js
This was created in https://github.com/openactive/openactive-test-suite/pull/306 and needs to be used for https://github.com/openactive/openactive-test-suite/pull/288
=> refactor: Create simulateActionAndExpectOrderFeedUpdateAfterSimpleC1C2B test recipe

packages/openactive-integration-tests/test/features/approval/minimal-proposal/implemented/accept-proposal-book-test.js, packages/openactive-integration-tests/test/features/payment/common.js, packages/openactive-integration-tests/test/helpers/flow-stages/book-recipe.js, packages/openactive-integration-tests/test/helpers/flow-stages/flow-stage-recipes.js, packages/openactive-integration-tests/test/helpers/flow-stages/flow-stage-utils.js, packages/openactive-integration-tests/test/shared-behaviours/validation.js
Add test to ensure that OrderProposal is always deleted after B, as per the spec.
This is also important to ensure that this change in the Orders Feed is collected explicitly before the next call is made, to avoid a race condition where the "delete" is actually picked up by any subsequent listeners.
=> feat: Delete check for proposal

packages/openactive-integration-tests/test/helpers/flow-stages/flow-stage-recipes.js, packages/openactive-integration-tests/test/helpers/flow-stages/order-feed-update.js
Without the fix, if I force a fail at P, the tests stop and timeout as they wait for that OrderProposal feed update that will never come. This leads to very slow feedback for anyone implementing approvals:
With the fix, later tests fail early:
Much quicker ☺️
=> fix: Use failEarlyIf to stop test timeouts waiting for Order Feed updates that are never going to come after failed P

packages/openactive-integration-tests/test/helpers/logger.js, packages/openactive-integration-tests/test/helpers/request-helper.js, packages/openactive-integration-tests/test/report-templates/report.md.handlebars
Added the following message error for the case where a feed item cannot be found:
> This response is still pending because the Broker Microservice at `http://localhost:3000/` is still waiting for the `@id` `{{{ requestMetadata.feedExtract.id }}}` to appear in the {{{ requestMetadata.feedExtract.type }}} feed(s).
> 
> To troubleshoot this, try opening the last pages of the relevant {{{ requestMetadata.feedExtract.type }}} feed(s) (which will be empty) in Postman or similar, then refreshing that page after this test has run. Check that the `@id` exactly matches `{{{ requestMetadata.feedExtract.id }}}`. If the item does not appear at the end of the feed check that the `modified` timestamp of the RPDE item is being updated, and that the `next` url on each page in the feed is correctly …
=> feat: Better error for feed collection

packages/openactive-broker-microservice/.eslintrc.json, packages/openactive-broker-microservice/app.js, packages/openactive-broker-microservice/src/apiConfig.js, packages/openactive-broker-microservice/src/models/FeedContext.d.ts, packages/openactive-broker-microservice/src/state.js, packages/openactive-broker-microservice/src/util/log.js, packages/openactive-broker-microservice/tsconfig.json
Why?
* I personally find it easier to find out what's going on as previously the state was in quite a few places
* Hopefully this will make it easier in future to move broker to a place where we can separate domain logic and side effects, making it easier to test, split apart and reason about
=> refactor: Move broker global state into one place

packages/openactive-broker-microservice/.eslintrc.json, packages/openactive-broker-microservice/app.js, packages/openactive-broker-microservice/package-lock.json, packages/openactive-broker-microservice/package.json, packages/openactive-broker-microservice/src/onePhaseListeners.js, packages/openactive-broker-microservice/src/order-uuid-tracking/api.js, packages/openactive-broker-microservice/src/order-uuid-tracking/order-uuid-tracking.js, packages/openactive-broker-microservice/src/state.js, packages/openactive-broker-microservice/src/twoPhaseListeners/api.js, packages/openactive-broker-microservice/src/twoPhaseListeners/twoPhaseListeners.js, packages/test-interface-criteria/built-types/index.d.ts, packages/test-interface-criteria/src/index.js
Functionality in Broker to listen for an Opportunity and only return when it finds that Opportunity with the expected remainingCapacity
Relates to https://github.com/openactive/openactive-test-suite/issues/460
Used with `expectedCapacity=<the actual amount that it's at>`. It returns correctly 👍 
Used with `expectedCapacity=<a different amount than it actually is at>`. It just waits until timeout. Here it is waiting for a bit:
https://user-images.githubusercontent.com/2067438/135105418-cb3e0af2-a09e-4d47-a13b-23cd6789c2c6.mov
=> feat(broker): Listen for Opportunity with given remainingCapacity

packages/openactive-broker-microservice/src/validator/validator-worker-pool.js, packages/openactive-broker-microservice/src/validator/validator-worker.js
This means that the worker pool only needs to send the file path to the worker rather than the whole file, which gets cloned.
This seems to also fix an intermittent issue in which validator input data is sometimes truncated (and therefore fails JSON parsing)
---
I've not been able to find anything about node.js truncating `workerData` input, but I've empirically seen it happen on my machine (sometimes). It seems that, under certain circumstances (?) it may impose a length limit on the data that it sends.
Regardless, now that I've learned that `workerData` is cloned before sending to a worker (https://nodejs.org/api/worker_threads.html#workerworkerdata), the code herein should be somewhat more optimised as it is only a file path that is cloned rather than a string containing 100 …
=> fix(broker): Read validator input file in worker rather than in worker pool

packages/openactive-broker-microservice/app.js
fixes #484 
FacilityUse feeds with embedded individualFacilityUse data need to be
inverted so the IndividualFacilityUse is the top-level parent kind for
many of the tests to work.
Validations are still performed on the original non-inverted feed.
=> Support for IndividualFacilityUse Slots

package.json, packages/openactive-broker-microservice/auto-restart.sh, packages/openactive-broker-microservice/package.json
Allows the broker to restart itself if it crashes (e.g if its buckets expire), which is useful in some deployment scenarios
=> feat: Auto-restart broker

packages/test-interface-criteria/built-types/criteria/TestOpportunityBookableCancellable.d.ts, packages/test-interface-criteria/built-types/criteria/TestOpportunityBookableFree.d.ts, packages/test-interface-criteria/built-types/criteria/TestOpportunityBookableFreeCancellable.d.ts, packages/test-interface-criteria/built-types/criteria/TestOpportunityBookableNonFree.d.ts, packages/test-interface-criteria/built-types/criteria/TestOpportunityBookableNonFreeCancellable.d.ts, packages/test-interface-criteria/built-types/criteria/criteriaUtils.d.ts, packages/test-interface-criteria/built-types/testDataShape.d.ts, packages/test-interface-criteria/src/criteria/TestOpportunityBookableCancellable.js, packages/test-interface-criteria/src/criteria/TestOpportunityBookableFree.js, packages/test-interface-criteria/src/criteria/TestOpportunityBookableFreeCancellable.js, packages/test-interface-criteria/src/criteria/TestOpportunityBookableNonFree.js, packages/test-interface-criteria/src/criteria/TestOpportunityBookableNonFreeCancellable.js, packages/test-interface-criteria/src/criteria/criteriaUtils.js, packages/test-interface-criteria/src/criteria/index.js, packages/test-interface-criteria/src/testDataShape.js
Implements https://github.com/openactive/test-interface/pull/18 in the Broker Microservice, which enables the implementation of https://github.com/openactive/openactive-test-suite/issues/548 at a later date.
Here is Broker Microservice configured against https://github.com/openactive/OpenActive.Server.NET (with a small random sample set). You can see that Broker has filtered some Opportunities into each of the new criteria:
The results of calling the Sample Oportunities endpoint with `test:testOpportunityCriteria` set to `TestOpportunityBookableNonFreeCancellable`:
Same for the `TestOpportunityBookableFreeCancellable`:
=> feat(criteria): Add TestOpportunityBookable(Non)FreeCancellable criterias

packages/openactive-broker-microservice/README.md, packages/openactive-broker-microservice/app.js, packages/openactive-broker-microservice/src/broker-config.js, packages/openactive-broker-microservice/src/models/core.d.ts
Currently the Booking Partner identifiers are hardcoded to be `primary` and `secondary` regardless of if these are set in config. When there was no `secondary` booking partner config set, this results in requests hitting the maximum retries and the app crashing. 
This fix gets the booking partner identifiers from config and only uses the ones set there.
Before
Now:
=> feat: get broker booking partner identifiers from config

packages/openactive-broker-microservice/package-lock.json, packages/openactive-broker-microservice/package.json, packages/openactive-integration-tests/package-lock.json, packages/openactive-integration-tests/package.json
Reverts openactive/openactive-test-suite#556
This needs to be reverted until `value` is removed from `accessCode` PropertyValues in OpenActive.Server.NET. Otherwise, most tests fail when run against OpenActive.Server.NET, which means that the CI of both projects is broken
This revert can be un-reverted once this issue has been complete: https://github.com/openactive/OpenActive.Server.NET/issues/213
=> Revert "Update data models"

packages/openactive-integration-tests/test-data-generator/test-data-generator.js, packages/openactive-integration-tests/test/helpers/test-interface-opportunities.js
Relates to https://github.com/openactive/test-interface/issues/21
Previously, even if useShapeExpressions was configured to true, Test Data Generator would not output shape expressions. This would have been a bug introduced by https://github.com/openactive/openactive-test-suite/pull/588.
This PR fixes that
=> fix(test-data-generator): Show Shape Expressions if integrationTests.useShapeExpressions is configured

packages/openactive-broker-microservice/src/broker-config.js, packages/openactive-broker-microservice/src/core.js, packages/openactive-broker-microservice/src/state.js, packages/openactive-broker-microservice/src/util/criteria-oriented-opportunity-id-cache.js
Closes https://github.com/openactive/openactive-test-suite/issues/668
(also, this includes a small amount of work to elaborate TODOs: https://github.com/openactive/openactive-test-suite/issues/667)
The purpose is to make it clearer what all the various ES Maps are in the Broker state and why there are so many data structures holding data that relates to the caching of opportunities.
This work also ellucidated that the opportunity data is duplicated. An issue has been made for that here: https://github.com/openactive/openactive-test-suite/issues/669
=> chore(broker): Categorise opportunity caches

.github/workflows/code-tests.yml, .github/workflows/create-data-model-pr.yaml, .github/workflows/docker.yml, .github/workflows/reference-implementation.yml
Update GitHub Actions references to resolve deprecation errors
=> fix: Update GitHub Actions references to latest versions

packages/openactive-integration-tests/test/features/cancellation/customer-requested-cancellation/implemented/atomic-cancel-test.js, packages/openactive-integration-tests/test/features/cancellation/customer-requested-cancellation/implemented/book-and-cancel-test.js, packages/openactive-integration-tests/test/helpers/flow-stages/flow-stage-recipes.js
Implements #698 for customer-requested cancellations
I tested this against a booking system which is not yet stable, but was able to gain confidence that the feature works as expected.
These screenshots demonstrate some of this. They are a side-by-side comparison of the results for the `book-and-cancel` test. The LHS includes the changes and the RHS does not:
**Single mode**: 
Here, the booking system failed to produce the CustomerCancelled order feed change in the LHS test, but this lead to it failing at the order feed download step, as it could never be found. Whereas, in the RHS test, Test Suite passes the order feed download step but then later fails when asserting about orderItemStatuses
**Multiple mode**: 
Here, the booking system succeeded in producing the CustomerCancelled order …
=> feat: Use ListenerItemExpectations for customer cancel

README.md, action.yml, docker-entrypoint.sh
Allow OpenActive Test Suite to be run from GitHub Actions
=> feat: GitHub actions support

packages/openactive-feed-snapshot-validator/src/app.js
What the results look like when there are no RPDE errors:
=> Feed Snapshot Checker: Compile all errors into a resulting data format
