openactive/openactive-test-suite

README.md
packages/openactive-broker-microservice/README.md
packages/openactive-broker-microservice/package.json
packages/openactive-integration-tests/DEVELOPMENT.md
packages/openactive-integration-tests/README.md
packages/openactive-integration-tests/package.json

Added some documentation around usage, and code structure.

Documentation

---

packages/openactive-integration-tests/babel.config.js
packages/openactive-integration-tests/package-lock.json
packages/openactive-integration-tests/package.json
packages/openactive-integration-tests/test/flows/book-and-cancel/book-and-customer-cancel-failure/book-shared.js
packages/openactive-integration-tests/test/flows/book-and-cancel/book-and-customer-cancel-success/book-shared.js
packages/openactive-integration-tests/test/flows/confirm-availability/availability-confirmed/book-shared.js
packages/openactive-integration-tests/test/flows/confirm-availability/no-spaces-available/book-shared.js
packages/openactive-integration-tests/test/flows/test-interface/session-test.js
packages/openactive-integration-tests/test/helpers/flow-helper.js
packages/openactive-integration-tests/test/helpers/request-helper.js
packages/openactive-integration-tests/test/helpers/request-state-helper.js
packages/openactive-integration-tests/test/helpers/request-state.js
packages/openactive-integration-tests/test/shared-behaviours/validation.js

Moves the chaining and variable assignment / passing logic out of the individual test suites into a couple of helper classes.
- Request-State-Helper - helper object, implements most of the methods of the RequestHelper, however it keeps state on itself which it passes to the various requests, and stores extracted values from responses against itself.
- FlowHelper - it's only job is to run the various tasks in sequence. It wraps a provided Request-State-Helper
Addresses #10

Reduce duplication

---

packages/openactive-integration-tests/run-specific-test.sh

Adds a script useful for testing a specific test

feat: script to run specific tests

---

ROADMAP.md

Add reference to the project board and milestones

docs: Add reference to the project board

---

CONTRIBUTING.md

Updated to encourage PRs like this one https://github.com/openactive/openactive-test-suite/pull/83

docs: Lighter contribution requirements

---

.gitignore
README.md

Make config documentation more helpful

docs: Clarify README for deployment config

---

packages/openactive-integration-tests/documentation/generator.js
packages/openactive-integration-tests/test/helpers/feature-helper.js
packages/openactive-integration-tests/tsconfig.json

I was trying to understand how the "criteria required" parts of the docs were generated. Thought I might as well type the bits as I understand them

chore: Type the doc generator + improve feature helper types

---

CONTRIBUTING.md
package-lock.json
package.json

So that we don't have to remember to do this for new tests

chore: Generate docs as a precommit hook

---

packages/openactive-integration-tests/test/certification/README.md

fix: Fix to link in Certificates README

---

.github/workflows/reference-implementation.yml

This allows makes it easy to download the test output from CI runs

Store test output as artifacts

---

packages/openactive-integration-tests/test/helpers/logger.js
packages/openactive-integration-tests/test/report-generator.js
packages/openactive-integration-tests/test/report-templates/report.md.handlebars

This allows network errors etc to be included in the output

feat: Include request error in output

---

.github/workflows/reference-implementation.yml
.vscode/launch.json
packages/openactive-integration-tests/config/default.json
packages/openactive-integration-tests/package-lock.json
packages/openactive-integration-tests/package.json
packages/openactive-integration-tests/test/features/core/availability-check/implemented/availability-confirmed-test.js
packages/openactive-integration-tests/test/features/core/availability-check/implemented/opportunity-full-test.js
packages/openactive-integration-tests/test/helpers/request-helper.js
packages/openactive-integration-tests/test/report-templates/report.md.handlebars

Fix issues with tests relating to FacilityUse
Also fixes issue with request body output that was introduced in #161

feat: Improve robustness of coverage for FacilityUse

---

packages/openactive-integration-tests/DEVELOPMENT.md

Clarifies documentation of the test file naming convention and directory structure

Improve documentation of test path naming convention

---

packages/openactive-integration-tests/test/features/cancellation/seller-requested-cancellation-message/README.md
packages/openactive-integration-tests/test/features/cancellation/seller-requested-cancellation-message/implemented/seller-requested-cancellation-with-message-test.js
packages/openactive-integration-tests/test/helpers/flow-stages/b.js
packages/openactive-integration-tests/test/helpers/flow-stages/test-interface-action.js

feat(cancellation): Complete seller-requested-cancellation-message test using FlowStages

---

packages/openactive-integration-tests/test/helpers/flow-stages/flow-stage-recipes.js
packages/openactive-integration-tests/test/helpers/flow-stages/index.js

for simple FetchOpportunities -> C1 -> C2 -> B flows
----
closes https://github.com/openactive/openactive-test-suite/issues/270
This function is tested in: https://github.com/openactive/openactive-test-suite/pull/287

chore: Create FlowStageRecipes.initialiseSimpleC1C2BFlow()

---

packages/openactive-integration-tests/test/helpers/flow-stages/b.js
packages/openactive-integration-tests/test/helpers/flow-stages/c1.js
packages/openactive-integration-tests/test/helpers/flow-stages/c2.js
packages/openactive-integration-tests/test/helpers/flow-stages/flow-stage-recipes.js
packages/openactive-integration-tests/test/helpers/request-helper.js
packages/openactive-integration-tests/test/helpers/request-state.js
packages/openactive-integration-tests/test/shared-behaviours/errors.js
packages/openactive-integration-tests/test/templates/b-req.js
packages/openactive-integration-tests/test/templates/c1-req.js
packages/openactive-integration-tests/test/templates/c2-req.js

Framework stuff from https://github.com/openactive/openactive-test-suite/pull/298 (without committing the tests themselves)

refactor: Support brokerRole and improve error handling

---

packages/openactive-integration-tests/test/helpers/flow-stages/b.js
packages/openactive-integration-tests/test/templates/b-req.js

plucked from https://github.com/openactive/openactive-test-suite/pull/306

chore(b): Support accessPass

---

packages/openactive-integration-tests/test/features/details-capture/additional-details-capture/implemented/additional-details-required-and-supplied-test.js

PropertyValueSpecification validation based on openactive/data-model-validator#367

fix: PropertyValueSpecification validation

---

packages/openactive-broker-microservice/app.js
packages/openactive-broker-microservice/config/default.json
packages/openactive-broker-microservice/package-lock.json
packages/openactive-broker-microservice/package.json
packages/openactive-broker-microservice/templates/validation-errors.handlebars
packages/openactive-broker-microservice/validator/async-validator.js
packages/openactive-broker-microservice/validator/validator-worker.js
packages/openactive-integration-tests/test/global-setup.js

Add inline validation to feeds, which closes #89

feat: Validation of opportunity feeds

---

.vscode/launch.json
config/default.json
package-lock.json
package.json
packages/openactive-broker-microservice/app.js
packages/openactive-integration-tests/test/report-templates/report.md.handlebars
start.js

Fixes https://github.com/openactive/openactive-test-suite/issues/420

feat: Better RPDE error handling

---

packages/openactive-integration-tests/test/features/access/access-channel-update-notifications/implemented/access-channel-update-notifications-test.js
packages/openactive-integration-tests/test/features/cancellation/cancellation-window/implemented/fail-outside-window-test.js
packages/openactive-integration-tests/test/features/cancellation/cancellation-window/implemented/succeed-within-window-test.js
packages/openactive-integration-tests/test/features/cancellation/customer-requested-cancellation/implemented/atomic-cancel-test.js
packages/openactive-integration-tests/test/features/cancellation/customer-requested-cancellation/implemented/book-and-cancel-test.js
packages/openactive-integration-tests/test/features/cancellation/customer-requested-cancellation/implemented/patch-contains-excessive-properties-error-test.js
packages/openactive-integration-tests/test/features/cancellation/customer-requested-cancellation/implemented/patch-not-allowed-on-property-error-test.js
packages/openactive-integration-tests/test/features/cancellation/seller-requested-cancellation-message/implemented/seller-requested-cancellation-with-message-test.js
packages/openactive-integration-tests/test/features/cancellation/seller-requested-cancellation/implemented/seller-requested-cancellation-test.js
packages/openactive-integration-tests/test/features/core/order-deletion/implemented/order-delete-idempotent-test.js
packages/openactive-integration-tests/test/features/core/order-deletion/implemented/orders-updated-then-deleted-test.js
packages/openactive-integration-tests/test/features/notifications/change-of-logistics-notifications/implemented/change-of-logistics-notifications-test.js
packages/openactive-integration-tests/test/shared-behaviours/test-recipes.js

rather than bookRecipe.b, which is not always the last stage

fix: use bookRecipe.lastStage as prerequisite to later stages

---

packages/openactive-integration-tests/README.md

including authentication, tax mode and payment reconciliation

docs(test-suite): Document the current configuration for Sellers

---

packages/openactive-openid-test-client/README.md
packages/openactive-openid-test-client/package.json

And:
* docs(openid-test-client): Describe Redirect URI set up to help with allowlisting

 fix(openid-test-client): Fix start script

---

package.json
packages/openactive-broker-microservice/package-lock.json
packages/openactive-integration-tests/package-lock.json
packages/openactive-openid-test-client/built-types/lib/auth-key-manager.d.ts
packages/openactive-openid-test-client/built-types/lib/client.d.ts
packages/openactive-openid-test-client/built-types/lib/index.d.ts
packages/openactive-openid-test-client/built-types/lib/request-intercept.d.ts
packages/openactive-openid-test-client/lib/browser-automation-for-auth.js
packages/openactive-openid-test-client/package-lock.json
packages/openactive-openid-test-client/package.json

Sometimes Chrome will freeze on browser.newPage on the older version of
puppeteer. https://github.com/puppeteer/puppeteer/issues/4039
Also required upgrading the typescript version on open-id-client.

fix: Upgrade puppeteer else chrome freezes on auth

---

packages/openactive-broker-microservice/app.js
packages/test-interface-criteria/src/criteria/criteriaUtils.js

Fix for handling IndividualFacilityUse in `criteriaUtils.js`

fix: IndividualFacilityUse

---

packages/openactive-broker-microservice/app.js

fix: @context for IndividualFacilityUse

---

packages/openactive-broker-microservice/README.md
packages/openactive-broker-microservice/app.js
packages/openactive-broker-microservice/package-lock.json
packages/openactive-broker-microservice/package.json
packages/openactive-integration-tests/package-lock.json
packages/openactive-integration-tests/package.json
packages/openactive-integration-tests/test/certification/certification-writer.js
packages/openactive-integration-tests/test/features/core/dataset-site/implemented/dataset-site-jsonld-valid-test.js
packages/openactive-integration-tests/test/global-setup.js

Update in line with https://github.com/openactive/data-models/pull/99

Update data model and data model validator dependencies (#498)

---

packages/openactive-integration-tests/test/features/core/amending-order-quote/implemented/amend-c2-test.js
packages/openactive-integration-tests/test/features/details-capture/customer-details-capture-non-essential/implemented/non-essential-customer-details-reflected-test.js

As the email is a composition of the first name (first letter in upper case), it will fail if the system tries to store it in lowercase

force email as lowercase

---

packages/openactive-integration-tests/ARCHITECTURE.md

Closes #559 
An explanation of the Flow Stages is being handled in #558 . Many of the helpers were already documented sufficiently (but happy to be convinced otherwise), so I mostly expanded FeatureHelper and added docs for DocumentationGenerator

docs: Ensure all important helpers are documented in ARCHITECTURE.md

---

packages/test-interface-criteria/src/criteria/TestOpportunityBookable.js
packages/test-interface-criteria/src/criteria/TestOpportunityBookableAdditionalDetails.js
packages/test-interface-criteria/src/criteria/TestOpportunityBookableAttendeeDetails.js
packages/test-interface-criteria/src/criteria/TestOpportunityBookableInPast.js
packages/test-interface-criteria/src/criteria/TestOpportunityBookableNoSpaces.js
packages/test-interface-criteria/src/criteria/TestOpportunityBookableNonFreePrepaymentUnavailable.js
packages/test-interface-criteria/src/criteria/TestOpportunityBookableOneSpace.js
packages/test-interface-criteria/src/criteria/TestOpportunityBookableOutsideValidFromBeforeStartDate.js
packages/test-interface-criteria/src/criteria/TestOpportunityBookableWithinValidFromBeforeStartDate.js

fix: Remove conflicting booking window constraint

---

packages/openactive-integration-tests/test/features/details-capture/customer-details-capture-non-essential/implemented/non-essential-customer-details-reflected-test.js
packages/openactive-integration-tests/test/helpers/flow-stages/flow-stage-recipes.js
packages/openactive-integration-tests/test/helpers/flow-stages/flow-stage-utils.js

feat: Randomly exclude optional customer fields

---

packages/openactive-broker-microservice/README.md
packages/openactive-integration-tests/package-lock.json

Closes https://github.com/openactive/openactive-test-suite/issues/635

docs(broker): Fix links to openactive-openid-* packages

---

package-lock.json
packages/openactive-broker-microservice/.eslintrc.json
packages/openactive-broker-microservice/README.md
packages/openactive-broker-microservice/app.js
packages/openactive-broker-microservice/package-lock.json
packages/openactive-broker-microservice/package.json
packages/openactive-broker-microservice/src/broker-config.js
packages/openactive-broker-microservice/src/core.js
packages/openactive-broker-microservice/src/incomplete-feeds.js
packages/openactive-broker-microservice/src/models/core.d.ts
packages/openactive-broker-microservice/src/state.js
packages/openactive-broker-microservice/src/twoPhaseListeners/api.js
packages/openactive-broker-microservice/src/validator/validator-worker-pool.js

Also:
* fix logging for fatal harvestRPDE errors
* Document "validation only" mode
* Some function/variable renamings to make things clearer
* A small amount of refactorings to make things clearer (but gave this up shortly due to time usage). Instances where this has happened
* Moved `incompleteFeeds` handling into a class with hopefully clearer semantics
---
**To the reviewer**: Don't forget to hide whitespace changes to reduce your workload by at least 300 lines!!
----
* Closes #637
* Closes #651 
* Closes #650 
* Closes #652

chore(broker): Add code comments and TypeScript types

---

packages/openactive-broker-microservice/src/core.js

feature: fix validation-errors.handlebars path

---

packages/openactive-broker-microservice/src/util/log.js

docs: Explain logging
